name: Deploy Fashion Spy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.2
      - name: Install dependencies and build
        run: |
          echo "NODE_ENV=production" > .env
          bun install
          bun run build
      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "*,!node_modules,!.env,"
          target: ${{ secrets.APP_DIR }}
          overwrite:
      - name: Install dependencies and restart app
        uses: appleboy/ssh-action@master
        with:
          port: ${{ secrets.SSH_PORT }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export BUN_INSTALL="$HOME/.bun"
            export PATH="$BUN_INSTALL/bin:$PATH"

            cd /home/matt/fashion-spy
            bun install --production 
            pm2 restart fashion-spy --update-env
